name: build

on:
  workflow_run:
    workflows: [Fork builds]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Print variables"
        uses: actions/github-script@v5
        with:
          script: |
            console.log("ROPO")
            console.log(context.payload.workflow_run)
