name: Build

on:
  workflow_run:
    workflows: [Fork]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Print context"
        uses: actions/github-script@v5
        with:
          script: |
            console.log(context.payload)
